# Generated by Django 3.2.8 on 2021-11-23 03:30

import django
from django.db import migrations, models

# Determine correct keyword argument based on the running Django version
# Django 5.1+ introduces condition=, and Django 6.0+ removes check=
constraint_kwargs = {"name": "backup_and_sha_not_null"}
q_expression = models.Q(("backup__isnull", False), ("sha__isnull", False))

if django.VERSION >= (5, 1):
    constraint_kwargs["condition"] = q_expression
else:
    constraint_kwargs["check"] = q_expression


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_config_backup', '0003_primary_model_to_bigid'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='backupcommit',
            # Unpack the dynamically generated arguments dictionary
            constraint=models.CheckConstraint(**constraint_kwargs),
        ),
    ]
