# Generated by Django 5.2b1 on 2025-06-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_config_backup", "0020_clean_rq_queue"),
    ]

    operations = [
        migrations.AddField(
            model_name="backupfile",
            name="last_change",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
