# Generated by Django 5.2.4 on 2025-08-10 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_config_backup', '0021_backupfile_last_change'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backupcommit',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='backupcommittreechange',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='backupfile',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='backupobject',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='backup',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='backupjob',
            options={'ordering': ('pk',)},
        ),
    ]
