# Generated by Django 5.2.5 on 2026-01-07 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_config_backup', '0022_model_ordering'),
        ('users', '0015_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='owner',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.owner'
            ),
        ),
    ]
