# Generated by Django 5.2.13 on 2026-05-26 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_config_backup', '0023_netbox_v040500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupcommittreechange',
            name='new',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='changes',
                to='netbox_config_backup.backupobject',
            ),
        ),
        migrations.AlterField(
            model_name='backupcommittreechange',
            name='old',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='previous',
                to='netbox_config_backup.backupobject',
            ),
        ),
    ]
