name: Auto approve
on:
  pull_request:
    types:
      - opened
    branches:
      - "master"

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.actor == 'dansheps'
    steps:
      - uses: hmarr/auto-approve-action@v4